// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSOHXPIPheQ9ahaJ9aoBBgePDcXANCQXo',
    appId: '1:623216205399:web:9e82c4ff58639de65ecd12',
    messagingSenderId: '623216205399',
    projectId: 'ia-tennis1',
    authDomain: 'ia-tennis1.firebaseapp.com',
    storageBucket: 'ia-tennis1.appspot.com',
    measurementId: 'G-444JLF3CL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDREtY6xoiJ6qubp3mqPU1KNzRgdwB1IQs',
    appId: '1:623216205399:android:95ed33e4e8ebc6fd5ecd12',
    messagingSenderId: '623216205399',
    projectId: 'ia-tennis1',
    storageBucket: 'ia-tennis1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpq7rCMG2KGtBkUsIcXl4VCzj8_vKkp1o',
    appId: '1:623216205399:ios:a92bca475dec892a5ecd12',
    messagingSenderId: '623216205399',
    projectId: 'ia-tennis1',
    storageBucket: 'ia-tennis1.appspot.com',
    iosBundleId: 'com.example.aiTennis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpq7rCMG2KGtBkUsIcXl4VCzj8_vKkp1o',
    appId: '1:623216205399:ios:a92bca475dec892a5ecd12',
    messagingSenderId: '623216205399',
    projectId: 'ia-tennis1',
    storageBucket: 'ia-tennis1.appspot.com',
    iosBundleId: 'com.example.aiTennis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSOHXPIPheQ9ahaJ9aoBBgePDcXANCQXo',
    appId: '1:623216205399:web:36942c63a3d3599f5ecd12',
    messagingSenderId: '623216205399',
    projectId: 'ia-tennis1',
    authDomain: 'ia-tennis1.firebaseapp.com',
    storageBucket: 'ia-tennis1.appspot.com',
    measurementId: 'G-W8K6S10MQW',
  );
}
